[metrics]
# Exposes Prometheus metrics
go_process = true

# API server
[service]
# Host and port
address = ":5001"

[chain]
start_block = 24873500
graphql_endpoint = ""
ws_endpoint = "wss://ws.celo.grassecon.net"
rpc_endpoint = "https://celo.grassecon.net"
testnet = false
registry_address = ""
