[metrics]
go_process = true

[api]
address = ":5001"

[chain]
ws_endpoint = "wss://ws.celo.grassecon.net"
rpc_endpoint = "https://celo.grassecon.net"
testnet = false
realtime = true
historical = false
start_block = 25151040
batch_size = 100

[bootstrap]
# https://software.grassecon.org/addresses
ge_registries = [
    "0xd1FB944748aca327a1ba036B082993D9dd9Bfa0C",
    "0x0cc9f4fff962def35bb34a53691180b13e653030",
]
watchlist = [""]
blacklist = [""]

[jetstream]
enable = true
endpoint = "nats://127.0.0.1:4222"
persist_duration_hrs = 48
dedup_duration_hrs = 6
