[metrics]
# Exposes Prometheus metrics
go_process = true

# API server
[service]
# Host and port
address = ":5001"

[chain]
start_block = 24905000
graphql_endpoint = ""
ws_endpoint = "wss://ws.celo.grassecon.net"
rpc_endpoint = "https://rpc.ankr.com/celo/bae2b7745f52c50974d7ecb1a7c23dc05d9ab5b68caf498a7c73f09a3e8bc04a"
testnet = false
registry_address = ""
