[metrics]
go_process = true

[api]
address = ":5001"

[chain]
ws_endpoint = "wss://ws.celo.grassecon.net"
rpc_endpoint = "https://1rpc.io/celo"
testnet = false
realtime = true
historical = false
start_block = 24905000

[bootstrap]
# https://software.grassecon.org/addresses
ge_registries = [
    "0xd1FB944748aca327a1ba036B082993D9dd9Bfa0C",
    "0x0cc9f4fff962def35bb34a53691180b13e653030",
]
watchlist = [""]
blacklist = [""]
