services:
  redis:
    image: valkey/valkey:8-alpine
    restart: unless-stopped
    command: valkey-server --save 60 1 --loglevel warning
    volumes:
      - tracker-valkey:/data
    ports:
      - "127.0.0.1:6379:6379"
    healthcheck:
      test: ["CMD-SHELL", "valkey-cli ping | grep PONG"]
      interval: 10s
      timeout: 5s
      retries: 5
  nats:
    image: nats:2
    restart: unless-stopped
    command: -js -sd /tmp/nats/data -m 8222
    ports:
      - 0.0.0.0:4222:4222
      - 0.0.0.0:8222:8222      
volumes:
  tracker-valkey:
    driver: local